name: WordPress CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install

    - name: Run linting
      run: vendor/bin/phpcs --standard=WordPress .

    - name: Run tests
      run: vendor/bin/phpunit
 
